spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME}
    password: ${PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: Foodeals Client
  datasource:
    url: jdbc:postgresql://localhost:5432/foodeals-db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true

app:
  security:
    jwt:
      secret-key: 883e807d7ee46bfd82464d697b0e6455d32b8406c6ee3a36e4a97de7ab976198
      # 1 day
      expiration: 86400000
      refresh-token:
        # 7 days
        expiration: 604800000

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB

user:
  dir: C:/Users/nasri/eclipse-workspace/Foodeals-pro/foodeals-pro-api/
upload:

  directory:
    photos


web:
  resources:
    static-locations: file:${user.dir}/${upload.directory}/


  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: YOUR_FACEBOOK_APP_ID
            client-secret: YOUR_FACEBOOK_APP_SECRET
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            scope: email,public_profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v17.0/dialog/oauth
            token-uri: https://graph.facebook.com/v17.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture